server:
  port: 8081
spring:
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      # String values
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer

#      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer